import "server-only";

import type { AdminProperty } from "@/types/property";

const propertyPhotos = {
  apartment:
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
  apartmentAlt:
    "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
  house:
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
  houseAlt:
    "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
  shop:
    "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
  plot:
    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
};

export const placeholderProperties: AdminProperty[] = [
  {
    id: "dha-modern-flat",
    title: "Modern Apartment near DHA Phase 6",
    location: "DHA",
    area: "DHA Phase 6",
    address: "Street 12, Phase 6, DHA Karachi",
    price: 32500000,
    size: "1,650",
    sizeUnit: "Sq Ft",
    propertyType: "Flat",
    purpose: "Sale",
    status: "approved",
    isFeatured: true,
    featuredRank: 1,
    image: propertyPhotos.apartment,
    images: [
      propertyPhotos.apartment,
      propertyPhotos.apartmentAlt,
      propertyPhotos.houseAlt,
    ],
    description:
      "A polished apartment with open lounge space, covered parking, and quick access to main DHA roads.",
    features: ["Lift access", "Reserved parking", "Backup power", "Family building"],
    bedrooms: 3,
    bathrooms: 3,
    sellerName: "Adeel Khan",
    sellerContact: "+92 300 1111111",
    sellerWhatsapp: "+92 300 1111111",
    sellerEmail: "adeel@example.com",
    adminNotes: "High quality demo lead.",
    rejectionReason: "",
  },
  {
    id: "clifton-family-house",
    title: "Family House in Clifton Block 5",
    location: "Clifton",
    area: "Clifton Block 5",
    address: "Block 5, near Boat Basin, Clifton",
    price: 145000000,
    size: "500",
    sizeUnit: "Sq Yards",
    propertyType: "House",
    purpose: "Sale",
    status: "approved",
    isFeatured: true,
    featuredRank: 2,
    image: propertyPhotos.house,
    images: [propertyPhotos.house, propertyPhotos.houseAlt, propertyPhotos.apartment],
    description:
      "A calm family home with generous rooms, a private terrace, and easy access to Clifton amenities.",
    features: ["Corner house", "Private terrace", "Servant quarter", "Two kitchens"],
    bedrooms: 5,
    bathrooms: 6,
    sellerName: "Sara Ahmed",
    sellerContact: "+92 321 2222222",
    sellerWhatsapp: "+92 321 2222222",
    sellerEmail: "sara@example.com",
    adminNotes: "Owner is available for viewings on weekends.",
    rejectionReason: "",
  },
  {
    id: "bahria-rent-portion",
    title: "Fresh Portion in Bahria Town Karachi",
    location: "Bahria Town Karachi",
    area: "Precinct 10-A",
    address: "Precinct 10-A, Bahria Town Karachi",
    price: 95000,
    size: "1,200",
    sizeUnit: "Sq Ft",
    propertyType: "Portion",
    purpose: "Rent",
    status: "approved",
    isFeatured: true,
    featuredRank: 3,
    image: propertyPhotos.apartmentAlt,
    images: [
      propertyPhotos.apartmentAlt,
      propertyPhotos.apartment,
      propertyPhotos.house,
    ],
    description:
      "A clean rental portion in a secure community with nearby parks, shops, and family-friendly streets.",
    features: ["Separate entrance", "Near park", "Family neighborhood", "Ready to move"],
    bedrooms: 2,
    bathrooms: 2,
    sellerName: "Hamza Farooq",
    sellerContact: "+92 333 3333333",
    sellerWhatsapp: "+92 333 3333333",
    sellerEmail: "hamza@example.com",
    adminNotes: "Rental listing with complete details.",
    rejectionReason: "",
  },
  {
    id: "gulshan-shop-rent",
    title: "Ground Floor Shop in Gulshan-e-Iqbal",
    location: "Gulshan-e-Iqbal",
    area: "Block 13-D",
    address: "Main market lane, Block 13-D",
    price: 180000,
    size: "420",
    sizeUnit: "Sq Ft",
    propertyType: "Shop",
    purpose: "Rent",
    status: "approved",
    isFeatured: false,
    featuredRank: undefined,
    image: propertyPhotos.shop,
    images: [propertyPhotos.shop, propertyPhotos.apartmentAlt, propertyPhotos.houseAlt],
    description:
      "A compact retail shop on an active lane, suitable for boutique, office, or service business.",
    features: ["Ground floor", "Market frontage", "Separate meter", "Rolling shutter"],
    bathrooms: 1,
    sellerName: "Noman Siddiqui",
    sellerContact: "+92 345 4444444",
    sellerWhatsapp: "+92 345 4444444",
    sellerEmail: "noman@example.com",
    adminNotes: "Verify commercial maintenance charges.",
    rejectionReason: "",
  },
  {
    id: "scheme-33-plot",
    title: "Residential Plot in Scheme 33",
    location: "Scheme 33",
    area: "Saadi Garden",
    address: "Saadi Garden, Scheme 33",
    price: 18500000,
    size: "240",
    sizeUnit: "Sq Yards",
    propertyType: "Plot",
    purpose: "Sale",
    status: "approved",
    isFeatured: false,
    featuredRank: undefined,
    image: propertyPhotos.plot,
    images: [propertyPhotos.plot, propertyPhotos.house, propertyPhotos.apartment],
    description:
      "An approved residential plot placeholder with strong access to developing Karachi neighborhoods.",
    features: ["Leased plot", "Boundary wall", "Wide road", "Clear file"],
    sellerName: "Bilal Qureshi",
    sellerContact: "+92 300 5555555",
    sellerWhatsapp: "+92 300 5555555",
    sellerEmail: "bilal@example.com",
    adminNotes: "Plot file appears complete in placeholder data.",
    rejectionReason: "",
  },
  {
    id: "pending-demo-property",
    title: "Pending Demo Property",
    location: "Malir",
    area: "Model Colony",
    address: "Model Colony, Malir",
    price: 12000000,
    size: "120",
    sizeUnit: "Sq Yards",
    propertyType: "House",
    purpose: "Sale",
    status: "pending",
    isFeatured: false,
    featuredRank: undefined,
    image: propertyPhotos.houseAlt,
    images: [propertyPhotos.houseAlt, propertyPhotos.apartment],
    description:
      "This placeholder is pending and should not appear on public property pages.",
    features: ["Submitted for review", "Needs admin approval"],
    bedrooms: 3,
    bathrooms: 3,
    sellerName: "Maira Ali",
    sellerContact: "+92 311 6666666",
    sellerWhatsapp: "+92 311 6666666",
    sellerEmail: "maira@example.com",
    adminNotes: "Needs image verification before approval.",
    rejectionReason: "",
  },
  {
    id: "rejected-office-demo",
    title: "Office Space near Shahrah-e-Faisal",
    location: "Gulshan-e-Iqbal",
    area: "Civic Center",
    address: "Commercial block near Civic Center",
    price: 250000,
    size: "900",
    sizeUnit: "Sq Ft",
    propertyType: "Office",
    purpose: "Rent",
    status: "rejected",
    isFeatured: false,
    featuredRank: undefined,
    image: propertyPhotos.shop,
    images: [propertyPhotos.shop, propertyPhotos.apartmentAlt],
    description:
      "Rejected placeholder record used to shape admin status handling.",
    features: ["Lift", "Reception area", "Parking"],
    bathrooms: 1,
    sellerName: "Danish Raza",
    sellerContact: "+92 322 7777777",
    sellerWhatsapp: "+92 322 7777777",
    sellerEmail: "danish@example.com",
    adminNotes: "Rejected because documents are incomplete.",
    rejectionReason: "Incomplete ownership documents.",
  },
];
